server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}-${spring.application.instance_id:${random.value}}
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: MongoProjectOne
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: debug
constants:
  port: 8002
  status:
    blocked: Blocked
    active: Active
  client:
    personal:
      description: Personal
      type:
        normal: Normal
        vip: Vip
    enterprise:
      description: Enterprise
      type:
        normal: Normal
        pyme: Pyme
  services:
    prefix: http://
    url:
      gateway: localhost:7999
      client: localhost:8001
      passive: localhost:8002
      active: localhost:8003
    path:
      client: /api/client
      passive: /api/passive
      active: /api/active
