server:
  port: 7999
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/client/**
        - id: passive-service
          uri: lb://passive-service
          predicates:
            - Path=/api/passive/**
        - id: active-service
          uri: lb://active-service
          predicates:
            - Path=/api/active/**