server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eurekaserver:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
        - id: microservice-client
          uri: lb://microservice-client
          predicates:
            - Path=/api/banking/**
        - id: passive-service
          uri: lb://passive-service
          predicates:
            - Path=/api/passive/**
        - id: active-service
          uri: lb://active-service
          predicates:
            - Path=/api/active/**